### ISSUE TITLE
Not working with fullcalendar 2.5.0

### ISSUE THREAD

**Issue by kabus202** [mherrmann/fullcalendar-columns#17]
Hi,

I have a problem using this with fullcalendar 2.5.0

```
<!DOCTYPE html>
```

<html>
<head>
    <meta charset='utf-8' />
    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/fullcalendar.css' rel='stylesheet' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.js'></script>
    <script src='https://code.jquery.com/jquery-2.1.3.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.3.1/fullcalendar.js'></script>
    <script src='../js/plugin/fullcalendar/fullcalendar-columns.js'></script>
    <script>
        $(document).ready(function() {

```
        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'multiColAgendaDay,multiColAgendaWeek'
            },
            views: {
                multiColAgendaDay: {
                    type: 'multiColAgenda',
                    duration: { days: 1 },
                    numColumns: 2,
                    columnHeaders: ['First Column', 'Second Column']
                },
                multiColAgendaWeek: {
                    type: 'multiColAgenda',
                    duration: { weeks: 1 },
                    numColumns: 2,
                    columnHeaders: ['First', 'Second']
                }
            },
            allDaySlot: false,
            defaultView: 'multiColAgendaDay',
            defaultDate: '2015-02-12',
            editable: true,
            events: [
                {
                    title: 'Meeting 1',
                    start: '2015-02-12T10:30:00',
                    end: '2015-02-12T12:30:00',
                    column: 0
                },
                {
                    title: 'Meeting 2',
                    start: '2015-02-12T10:30:00',
                    end: '2015-02-12T12:30:00',
                    column: 1
                }
            ]
        });

    });
</script>
<style>
    body {
        margin: 40px 10px;
        padding: 0;
        font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
        font-size: 14px;
    }
    #calendar {
        max-width: 900px;
        margin: 0 auto;
    }
</style>
```

</head>
<body>

<div id='calendar'></div>

</body>
</html>

**Comment by mherrmann** [comment]
Hi kabus, thanks for letting me know. I am using v2.3.x in production and currently don't have time to upgrade to 2.5.0. If you want to submit a Pull Request that adds compatibility with v2.5.0 while maintaining compatibility with 2.3.x, I'd be happy to accept it!

**Comment by Trebor777** [comment]
It's crashing in 2.6.0 as well. 
fullcalendar-columns.js:20 Uncaught TypeError: Cannot read property 'views' of undefined

which then crash in fullcalendar.js:8563   itself: TypeError:  spec.class is not a function

Here's my coffeescript (just for test)

```
$(document).ready ->
  today = new Date()
  today.setHours(0,0,0,0)

  $("#calendar").fullCalendar(
    weekends: false # hide saturdays / sundays
    editable: true
    selectable: true
    lang: "fr"
    timezone: 'local'
    header:
      left: 'prev,next today'
      center: 'title'
      right:'month,multiColWeek,agendaDay'

    views:
      multiColWeek:
        type: 'multiColAgenda'
        duration:
          weeks : 1
        numColumns: 5
        columnHeaders : ['- 1 -','- 2 -','- 3 -','- 4 -','- 5 -']



    defaultView: 'multiColWeek'        #'agendaWeek'
    height: "auto"
    slotMinutes: 30
    aspectRatio: 2
    allDaySlot: false
    minTime: "07:00:00"
    maxTime: "21:30:00"
    nowIndicator: true
    timeFormat: 'HH:mm'
    columnFormat: 'dddd D/MM'
    titleFormat: 'D MMMM YYYY'
    dragOpacity: "0.5"
    eventConstraint:
      start: '07:00'
      end: '21:00'
`
```
